export { PreferredRoomsForActivity } from './space/activity/PreferredRoomsForActivity';
export { RoomNotAvailable } from './space/room/RoomNotAvailable';
export { ActivitiesNotOverlapping } from './time/activity/ActivitiesNotOverlapping';
export { MaxConsecutiveHoursForTeacher } from './time/teacher/MaxConsecutiveHoursForTeacher';
export { MinGapsBetweenActivities } from './time/activity/MinGapsBetweenActivities';
export { PreferredStartingTimesForActivity } from './time/activity/PreferredStartingTimesForActivity';
export { StudentSetNotAvailablePeriods } from './time/studentSet/StudentSetNotAvailablePeriods';
export { TeacherMaxDaysPerWeek } from './time/teacher/TeacherMaxDaysPerWeek';
export { TeacherNotAvailablePeriods } from './time/teacher/TeacherNotAvailablePeriods';
